import { Callout, SampleMediaItem } from '../types';

export const SAMPLE_MEDIA_LIST: SampleMediaItem[] = [
  {
    id: 'sample-peta-kota',
    title: 'Peta Fasilitas Kota & Wilayah',
    type: 'image',
    category: 'Peta & Fasilitas Publik',
    url: 'https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=1600&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=400&q=80',
    defaultCallouts: [
      {
        id: 'map-1',
        title: 'Pasar Sentral Niaga',
        description: 'Pusat belanja kebutuhan pokok dan sentra UMKM daerah.',
        badgeText: 'Pasar',
        category: 'sorotan',
        icon: 'store',
        targetX: 32,
        targetY: 46,
        cardPosition: 'top-left',
        theme: 'cyber',
        accentColor: '#f59e0b',
        animation: 'pulse',
        connectorType: 'straight',
        timestamp: 0,
        duration: 0,
        visible: true,
        boxType: 'none',
        titleAtLineEnd: true,
        lineWidth: 2.5,
        lineLength: 20
      },
      {
        id: 'map-2',
        title: 'Terminal Terpadu Antarkota',
        description: 'Hub transportasi massal bus antarkota dan transit cepat.',
        badgeText: 'Terminal',
        category: 'spek',
        icon: 'terminal',
        targetX: 68,
        targetY: 38,
        cardPosition: 'top-right',
        theme: 'neon',
        accentColor: '#06b6d4',
        animation: 'radar',
        connectorType: 'straight',
        timestamp: 0,
        duration: 0,
        visible: true,
        boxType: 'none',
        titleAtLineEnd: true,
        lineWidth: 2.5,
        lineLength: 22
      },
      {
        id: 'map-3',
        title: 'Halte Bus Utama Sudirman',
        description: 'Titik pemberhentian armada feeder dan bus listrik kota.',
        badgeText: 'Halte Bus',
        category: 'fitur',
        icon: 'bus',
        targetX: 48,
        targetY: 62,
        cardPosition: 'bottom-right',
        theme: 'glass',
        accentColor: '#3b82f6',
        animation: 'pulse',
        connectorType: 'straight',
        timestamp: 0,
        duration: 0,
        visible: true,
        boxType: 'none',
        titleAtLineEnd: true,
        lineWidth: 2.5,
        lineLength: 18
      },
      {
        id: 'map-4',
        title: 'Sekolah Menengah Unggulan',
        description: 'Kompleks pendidikan terpadu dengan laboratorium digital.',
        badgeText: 'Sekolah',
        category: 'fitur',
        icon: 'school',
        targetX: 24,
        targetY: 68,
        cardPosition: 'bottom-left',
        theme: 'badge',
        accentColor: '#8b5cf6',
        animation: 'glow',
        connectorType: 'straight',
        timestamp: 0,
        duration: 0,
        visible: true,
        boxType: 'none',
        titleAtLineEnd: true,
        lineWidth: 2.5,
        lineLength: 18
      },
      {
        id: 'map-5',
        title: 'Kantor Balai Kota & Pelayanan',
        description: 'Pusat administrasi pemerintahan dan pelayanan publik terpadu.',
        badgeText: 'Kantor',
        category: 'spek',
        icon: 'building',
        targetX: 52,
        targetY: 28,
        cardPosition: 'top-right',
        theme: 'cyber',
        accentColor: '#10b981',
        animation: 'radar',
        connectorType: 'straight',
        timestamp: 0,
        duration: 0,
        visible: true,
        boxType: 'none',
        titleAtLineEnd: true,
        lineWidth: 2.5,
        lineLength: 20
      },
      {
        id: 'map-6',
        title: 'Lapangan Olahraga & Stadion',
        description: 'Fasilitas lintasan lari, lapangan sepakbola, dan ruang terbuka hijau.',
        badgeText: 'Lapangan',
        category: 'sorotan',
        icon: 'lapangan',
        targetX: 78,
        targetY: 65,
        cardPosition: 'bottom-right',
        theme: 'neon',
        accentColor: '#f43f5e',
        animation: 'bounce',
        connectorType: 'straight',
        timestamp: 0,
        duration: 0,
        visible: true,
        boxType: 'none',
        titleAtLineEnd: true,
        lineWidth: 2.5,
        lineLength: 20
      }
    ]
  },
  {
    id: 'sample-smartwatch',
    title: 'Smartwatch Ultra Pro Titanium',
    type: 'image',
    category: 'Gadget & Teknologi',
    url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1600&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=400&q=80',
    defaultCallouts: [
      {
        id: 'c1',
        title: 'Layar AMOLED Retina 1.9"',
        description: 'Tingkat kecerahan hingga 2000 nits dengan kaca safir anti gores yang jernih di bawah sinar matahari langsung.',
        badgeText: 'Display 2000 Nits',
        category: 'fitur',
        icon: 'sparkles',
        targetX: 48,
        targetY: 42,
        cardPosition: 'top-left',
        theme: 'cyber',
        accentColor: '#06b6d4',
        animation: 'pulse',
        connectorType: 'angled',
        timestamp: 0,
        duration: 0,
        visible: true,
        actionUrl: 'https://google.com',
        actionLabel: 'Cek Spesifikasi'
      },
      {
        id: 'c2',
        title: 'Bodi Titanium Aerospace Grade',
        description: 'Tahan benturan ekstrem, tahan air hingga kedalaman 50 meter (5 ATM), dan ringan di pergelangan tangan.',
        badgeText: 'Bobot 48g',
        category: 'spek',
        icon: 'shield',
        targetX: 62,
        targetY: 55,
        cardPosition: 'bottom-right',
        theme: 'glass',
        accentColor: '#8b5cf6',
        animation: 'radar',
        connectorType: 'angled',
        timestamp: 0,
        duration: 0,
        visible: true
      },
      {
        id: 'c3',
        title: 'Sensor Detak Jantung & SpO2',
        description: 'Pemantauan biometrik presisi tinggi secara real-time 24/7 dengan notifikasi ritme detak jantung.',
        badgeText: 'Sensor Medis',
        category: 'fitur',
        icon: 'activity',
        targetX: 38,
        targetY: 58,
        cardPosition: 'bottom-left',
        theme: 'neon',
        accentColor: '#10b981',
        animation: 'glow',
        connectorType: 'angled',
        timestamp: 0,
        duration: 0,
        visible: true
      }
    ]
  },
  {
    id: 'sample-interior',
    title: 'Desain Interior Living Room Minimalis',
    type: 'image',
    category: 'Arsitektur & Desain',
    url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1600&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=400&q=80',
    defaultCallouts: [
      {
        id: 'int-1',
        title: 'Sofa Modular Linen Organik',
        description: 'Busa density tinggi dilapisi kain linen Belgia natural yang adem dan mudah dibersihkan.',
        badgeText: 'Rp 14.500.000',
        category: 'harga',
        icon: 'tag',
        targetX: 52,
        targetY: 65,
        cardPosition: 'top-right',
        theme: 'badge',
        accentColor: '#f59e0b',
        animation: 'pulse',
        connectorType: 'straight',
        timestamp: 0,
        duration: 0,
        visible: true,
        actionUrl: 'https://tokopedia.com',
        actionLabel: 'Beli Sekarang'
      },
      {
        id: 'int-2',
        title: 'Pencahayaan Alami Floor-to-Ceiling',
        description: 'Jendela kaca ganda berinsulasi panas memaksimalkan sirkulasi udara dan cahaya natural.',
        badgeText: 'Desain Biofilik',
        category: 'desain',
        icon: 'eye',
        targetX: 25,
        targetY: 35,
        cardPosition: 'bottom-right',
        theme: 'glass',
        accentColor: '#06b6d4',
        animation: 'glow',
        connectorType: 'angled',
        timestamp: 0,
        duration: 0,
        visible: true
      },
      {
        id: 'int-3',
        title: 'Lampu Gantung Nordic Geometris',
        description: 'Aksen kuningan brushed matte dengan fitting LED hangat 2700K yang ramah mata.',
        badgeText: 'Lampu Gantung',
        category: 'desain',
        icon: 'sparkles',
        targetX: 72,
        targetY: 28,
        cardPosition: 'bottom-left',
        theme: 'pop',
        accentColor: '#ec4899',
        animation: 'bounce',
        connectorType: 'arc',
        timestamp: 0,
        duration: 0,
        visible: true
      }
    ]
  },
  {
    id: 'sample-coffee',
    title: 'Mesin Kopi Espresso Komersial Pro',
    type: 'image',
    category: 'F&B & Peralatan',
    url: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&w=1600&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&w=400&q=80',
    defaultCallouts: [
      {
        id: 'cof-1',
        title: 'Dual Boiler PID Temperature Control',
        description: 'Stabilitas suhu ekstraksi hingga presisi 0.5°C untuk cita rasa espresso yang konsisten.',
        badgeText: 'Kontrol PID',
        category: 'spek',
        icon: 'cpu',
        targetX: 42,
        targetY: 35,
        cardPosition: 'top-left',
        theme: 'cyber',
        accentColor: '#3b82f6',
        animation: 'pulse',
        connectorType: 'angled',
        timestamp: 0,
        duration: 0,
        visible: true
      },
      {
        id: 'cof-2',
        title: 'Portafilter Stainless Steel 58mm',
        description: 'Standar barista kompetisi dengan basket presisi untuk ekstraksi crema maksimal.',
        badgeText: 'Diameter 58mm',
        category: 'fitur',
        icon: 'award',
        targetX: 62,
        targetY: 58,
        cardPosition: 'bottom-right',
        theme: 'badge',
        accentColor: '#eab308',
        animation: 'radar',
        connectorType: 'angled',
        timestamp: 0,
        duration: 0,
        visible: true
      }
    ]
  },
  {
    id: 'sample-drone-video',
    title: 'Footage Drone Pantai & Laut Tropis (Video)',
    type: 'video',
    category: 'Video Alam & Drone',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=400&q=80',
    defaultCallouts: [
      {
        id: 'vid-1',
        title: 'Pemandangan Garis Pantai Karang',
        description: 'Gradasi air laut toska jernih dengan formasi batuan karang vulkanik alami.',
        badgeText: 'Lokasi Eksotis',
        category: 'sorotan',
        icon: 'compass',
        targetX: 35,
        targetY: 48,
        cardPosition: 'top-right',
        theme: 'glass',
        accentColor: '#06b6d4',
        animation: 'pulse',
        connectorType: 'angled',
        timestamp: 1.5,
        duration: 5,
        visible: true
      },
      {
        id: 'vid-2',
        title: 'Penerbangan Drone 4K 60FPS',
        description: 'Stabilisasi gimbal 3-axis menangkap gerakan mulus dengan pencahayaan golden hour.',
        badgeText: 'Resolusi 4K',
        category: 'spek',
        icon: 'camera',
        targetX: 68,
        targetY: 30,
        cardPosition: 'bottom-left',
        theme: 'cyber',
        accentColor: '#10b981',
        animation: 'radar',
        connectorType: 'angled',
        timestamp: 3,
        duration: 6,
        visible: true
      }
    ]
  },
  {
    id: 'sample-motion-video',
    title: 'Video Demo Produk & Gerak Visual',
    type: 'video',
    category: 'Video Produk & Edukasi',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=400&q=80',
    defaultCallouts: [
      {
        id: 'vid-m1',
        title: 'Momen Aksi Berkecepatan Tinggi',
        description: 'Tangkap fokus objek bergerak menggunakan AI dynamic motion tracker.',
        badgeText: 'Auto Tracking',
        category: 'fitur',
        icon: 'zap',
        targetX: 50,
        targetY: 52,
        cardPosition: 'top-right',
        theme: 'neon',
        accentColor: '#f43f5e',
        animation: 'pulse',
        connectorType: 'angled',
        timestamp: 2,
        duration: 4.5,
        visible: true
      }
    ]
  }
];
